interface Coordinate {
    x: f32;
    y: f32;
}

interface SavedLocation {
    name: string;
    importance: i32;
    coord: Coordinate;
    starred: boolean;
    saved_at: Date;
}

interface Map {
    locations: SavedLocation[];
    user: string;
    default: SavedLocation;
    current: SavedLocation;
}

interface MapSketchyLocations {
    locations: SavedLocation?[]?;
    user: string;
    default: SavedLocation;
    current: SavedLocation?;
}

interface Endpoint {
    method: string;
    route: string;
    accessed_at: Date;
}

type NullableMapArrayArray = Map[]?[];
type NullableMapArray = Map?[];
